/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const path = require("path");
const fs = require("fs");
const app = express();

app.use(bodyParser.json());

// let todos = []
// let idReference = 1

// function autogenerateId(){
//   const newId = idReference
//   idReference += 1
//   return newId
// }

// app.get('/todos', (req,res)=>{
//   res.status(200).json(todos)
// })

// app.get('/todos/:id', (req,res)=>{
//   const demandedId = req.params.id;
//   const todo = todos.filter((item)=>{return item.id == demandedId})
//   if (todo.length == 0){
//     res.status(404).send("404 Not Found")
//   } else{
//     res.status(200).json(todo[0])
//   }
// })

// app.post('/todos', (req,res)=>{
//   const newTodo = req.body
//   newTodo.id = autogenerateId()
//   todos.push(newTodo)
//   res.status(201).json({id : newTodo.id})
// })

// app.put('/todos/:id', (req,res)=>{
//   const demandedTodoIndex = todos.findIndex((item)=> item.id == req.params.id)
//   if (demandedTodoIndex !== -1){
//     const updatedTodo = req.body
//     updatedTodo.id = todos[demandedTodoIndex].id
//     todos[demandedTodoIndex] = updatedTodo
//     res.status(200).send()
//   } else {
//     res.status(404).send()
//   }
// })

// app.delete('/todos/:id', (req,res)=>{
//   const newTodoArray = todos.filter((item)=>{return item.id != req.params.id})
//   if (todos.length === newTodoArray.length) {
//     res.status(404).send()
//   } else {
//     todos = newTodoArray
//     res.status(200).send()
//   }
// })

//  HARD TODO

let todos;

fs.readFile("todos.json", "utf8", (err, data) => {
  if (err) throw err;
  todos = JSON.parse(data);
});

app.get("/todos", (req, res) => {
  res.status(200).json(todos);
});

app.get("/todos/:id", (req, res) => {
  const requestedTodo = todos.find(
    (todo) => todo.id === parseInt(req.params.id)
  );
  if (!requestedTodo) {
    res.status(404).send("404 Not Found");
  } else {
    res.status(200).json(requestedTodo);
  }
});

app.post("/todos", (req, res) => {
  const newTodo = req.body;
  newTodo.id = Math.floor(Math.random() * 1000000);
  todos.push(newTodo);
  fs.writeFile("todos.json", JSON.stringify(todos), (err) => {
    if (err) throw err;
    res.status(201).json({ id: newTodo.id });
  });
});

app.put("/todos/:id", (req, res) => {
  const requiredId = req.params.id;
  const updatedTodo = req.body;
  const requestedTodoIndex = todos.findIndex(
    (item) => item.id === parseInt(requiredId)
  );
  if (requestedTodoIndex == -1) {
    res.status(404).send("404 Not Found");
  } else {
    updatedTodo.id = todos[requestedTodoIndex].id;
    todos[requestedTodoIndex] = updatedTodo;
    fs.writeFile("todos.json", JSON.stringify(todos), (err) => {
      if (err) throw err;
    });
    res.status(200).send();
  }
});

app.delete("/todos/:id", (req, res) => {
  const requestedId = req.params.id;
  const requestedTodoIndex = todos.findIndex(
    (item) => item.id === parseInt(requestedId)
  );
  if (requestedTodoIndex == -1) {
    res.status(404).send("404 Not Found");
  } else {
    todos.splice(requestedTodoIndex, 1);
    fs.writeFile("todos.json", JSON.stringify(todos), (err) => {
      if (err) throw err;
      res.status(200).send();
    });
  }
});

app.use((req, res, next) => {
  res.status(404).send();
});

app.listen(3000)

// NOTE : dont create a global read function, read in each route then write all functionality inside read because fs.read is async and it will make sure that the file has been read before doing anything

module.exports = app;


